#!/bin/bash

USERID=$(id -u)
SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-14} #if days are provided, the given dates will be considered, otherwise it will take 14 days (default) 

START_TIME=$(date +%s)
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
LOGS_FOLDER="/var/log/Roboshop-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

#validate functions takes input as exit status, what command they tried to install
VALIDATE(){
    if [ $1 -eq 0 ]
    then
        echo -e "$2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
    else 
        echo -e "$2 is ... $G FAILURE $N" | tee -a $LOG_FILE
        exit 1
    fi
}

check_root
if [ $USERID -ne 0 ]
then
    echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
    exit 1 #give other than 0 upto 127
else
    echo "you are running with root access" | tee -a $LOG_FILE
fi


check_root
mkdir -p $LOGS_FOLDER

USAGE(){
    echo -e "$R USAGE:: $N sh <filename> <source-dir> <destination-dir> <days>"
}

if [ $# -lt 2 ]
then 
   USAGE
fi

if [ ! -d $SOURCE_DIR ]
then
    echo -e "$R source directory $SOURCE_DIR does not exist. please check $N"
    exit 1
fi 

if [ ! -d $DEST_DIR ]
then
    echo -e "$R Destination directory $DEST_DIR does not exist. please check $N"
fi 

FILES=$(find $SOURCE_DIR -name "*.log" -mtime -$DAYS)

if [ ! -z $FILES ]
then
    echo "files to zip are: $FILES"
    TIMESTAMP=$(date +%F-%H-%M-%S)
    ZIP_FILE="$DEST_DIR/app-logs-$TIMESTAMP.zip"
    echo $FILES | zip -@ $ZIP_FILE

    if [ -f $ZIP_FILE ]
    then
       echo -e "succesfully created zip file"

       while IFS= read -r filepath
       do
           echo "deleting file: $filepath" | tee -a $LOG_FILE
           rm -rf $filepath
       done <<< $FILES
    else
       echo -e "Zip file creation ...$R failure $N"
       exit 1
    fi 
else 
   echo "No log files found older than 14 days ...$Y SKIPPING $N"
fi 