#!/bin/bash

Number=$1

if [ $Number -lt 10 ]
then
    echo "Given number $Number is less than 10"
else 
    echo "Given Number $Number is not less than 10"
fi

HE=$Idiot
if [ $HE -calls me  an idiot ]
then 
    echo "I will kill him"
else 
    echo "i will ignore him"
fi
