#!/bin/bash

echo "All variables passed to the script: $@"
echo "Number of variables: $#"
echo "script name: $0"
echo "present orking directory: $pwd"
echo "Home directory of the user: $HOME"
echo "user running the script: $USER"
echo "PID of the script: $$"
echo "PID of the last command running in background: $!"