#!/bin/bash

PERSON1=$1
PERSON2=$2

echo "$PERSON1:: Hi $PERSON2. how are you?"
echo "$PERSON2 :: Hi ra am fine how about you?"
echo "$PERSON1:: did you had your lunch , lets go and have it"
echo "$PERSON2:: okay raa"
echo "$PERSON1::please come to my place fast"